### ISSUE TITLE
Fix the broken preview on Vercel - Vercel needs to be linked to the repo 

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/ubiquity-dollar-development#178]

**Comment by 0x4007** [comment]
I looked into this and realized that we didn't have Vercel on here, as it is an organization repo, and Vercel charges money for organization repos. I suppose that we could look more into a strategy that leverages staging for the Vercel previews would be the move.

**Comment by Zequez** [comment]
Here is an alternative thought: We're funding the team with thousands of dollar monthly, would it be such a hit on the budget to just pay $20 and get a Vercel Pro account? 😆
We would save many hours in managing the complexity of using Vercel for free and we would be supporting the team that's managing a vital part of our infrastructure.

**Comment by 0x4007** [comment]
> Here is an alternative thought: We're funding the team with thousands of dollar monthly, would it be such a hit on the budget to just pay $20 and get a Vercel Pro account? 😆 We would save many hours in managing the complexity of using Vercel for free and we would be supporting the team that's managing a vital part of our infrastructure.
![frenworld_agadlgmaarqsqas](https://user-images.githubusercontent.com/4975670/171803808-cc9f347e-7d7a-4bb2-9f66-854bb90da14f.png)

**Comment by 0x4007** [comment]
Duplicate #187
